ERROR 2024-12-27 14:02:49,323 log Internal Server Error: /cms/article/
Traceback (most recent call last):
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\cms_app\views\article_api.py", line 40, in create
    request.data["author"] = request.user.id
    ~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 562, in __setitem__
    self._assert_mutable()
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 559, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2024-12-27 14:02:49,356 basehttp "POST /cms/article/ HTTP/1.1" 500 110769
ERROR 2024-12-27 14:05:50,723 log Internal Server Error: /cms/article/
Traceback (most recent call last):
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\cms_app\views\article_api.py", line 40, in create
    request.data["author"] = request.user.id
    ~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 562, in __setitem__
    self._assert_mutable()
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 559, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2024-12-27 14:05:50,754 basehttp "POST /cms/article/ HTTP/1.1" 500 110733
ERROR 2024-12-27 14:09:14,259 log Internal Server Error: /cms/article/
Traceback (most recent call last):
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\cms_app\views\article_api.py", line 40, in create
    request.data["author"] = request.user.id
    ~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 562, in __setitem__
    self._assert_mutable()
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 559, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2024-12-27 14:09:14,274 basehttp "POST /cms/article/ HTTP/1.1" 500 110733
ERROR 2024-12-27 14:12:14,512 log Internal Server Error: /cms/article/
Traceback (most recent call last):
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\cms_app\views\article_api.py", line 40, in create
    request.data["author"] = request.user.id
    ~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 562, in __setitem__
    self._assert_mutable()
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 559, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2024-12-27 14:12:14,543 basehttp "POST /cms/article/ HTTP/1.1" 500 110733
ERROR 2024-12-27 14:26:14,515 log Internal Server Error: /cms/article/
Traceback (most recent call last):
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\cms_app\views\article_api.py", line 40, in create
    request.data["author"] = request.user.id
    ~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 562, in __setitem__
    self._assert_mutable()
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 559, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2024-12-27 14:26:14,530 basehttp "POST /cms/article/ HTTP/1.1" 500 110757
ERROR 2024-12-27 14:54:01,779 log Internal Server Error: /cms/article/
Traceback (most recent call last):
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\cms_app\views\article_api.py", line 40, in create
    request.data["author"] = request.user.id
    ~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 562, in __setitem__
    self._assert_mutable()
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 559, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2024-12-27 14:54:01,809 basehttp "POST /cms/article/ HTTP/1.1" 500 110688
ERROR 2024-12-27 14:56:14,233 log Internal Server Error: /cms/article/
Traceback (most recent call last):
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\cms_app\views\article_api.py", line 40, in create
    request.data["author"] = request.user.id
    ~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 562, in __setitem__
    self._assert_mutable()
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 559, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2024-12-27 14:56:14,239 basehttp "POST /cms/article/ HTTP/1.1" 500 110688
ERROR 2024-12-27 14:58:00,574 log Internal Server Error: /cms/article/
Traceback (most recent call last):
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\cms_app\views\article_api.py", line 40, in create
    request.data["author"] = request.user.id
    ~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 562, in __setitem__
    self._assert_mutable()
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 559, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2024-12-27 14:58:00,582 basehttp "POST /cms/article/ HTTP/1.1" 500 110493
ERROR 2024-12-27 14:58:41,145 log Internal Server Error: /cms/article/
Traceback (most recent call last):
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\cms_app\views\article_api.py", line 40, in create
    request.data["author"] = request.user.id
    ~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 562, in __setitem__
    self._assert_mutable()
  File "D:\Project QNN\backend_gsip\env\Lib\site-packages\django\http\request.py", line 559, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2024-12-27 14:58:41,161 basehttp "POST /cms/article/ HTTP/1.1" 500 110493
